// Generated by gencpp from file first_tutorial/AddTwoInts.msg
// DO NOT EDIT!


#ifndef FIRST_TUTORIAL_MESSAGE_ADDTWOINTS_H
#define FIRST_TUTORIAL_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <first_tutorial/AddTwoIntsRequest.h>
#include <first_tutorial/AddTwoIntsResponse.h>


namespace first_tutorial
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace first_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::first_tutorial::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::first_tutorial::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::first_tutorial::AddTwoInts > {
  static const char* value()
  {
    return "first_tutorial/AddTwoInts";
  }

  static const char* value(const ::first_tutorial::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::first_tutorial::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::first_tutorial::AddTwoInts >
template<>
struct MD5Sum< ::first_tutorial::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::first_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::first_tutorial::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::first_tutorial::AddTwoIntsRequest> should match
// service_traits::DataType< ::first_tutorial::AddTwoInts >
template<>
struct DataType< ::first_tutorial::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::first_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::first_tutorial::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::first_tutorial::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::first_tutorial::AddTwoInts >
template<>
struct MD5Sum< ::first_tutorial::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::first_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::first_tutorial::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::first_tutorial::AddTwoIntsResponse> should match
// service_traits::DataType< ::first_tutorial::AddTwoInts >
template<>
struct DataType< ::first_tutorial::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::first_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::first_tutorial::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIRST_TUTORIAL_MESSAGE_ADDTWOINTS_H
